-- REVIEW 테이블 생성
CREATE TABLE REVIEW_TB (
	RV_NO INTEGER NOT NULL PRIMARY KEY,	/* 리뷰번호 */
	RV_DATE DATE DEFAULT SYSDATE,		/* 작성일자 */
	R_NO INTEGER NOT NULL,				/* 예약번호 */
	R_TIME VARCHAR2(20) NOT NULL,	    /* 예약시간 (날짜와 시간 포함) */
	R_SUBMIT_TIME DATE NOT NULL,		/* 예약버튼 누른 시간 */
	USER_ID VARCHAR2(20) NOT NULL,		/* 작성자ID */
	STORE_NAME VARCHAR2(400),			/* 방문매장명 */
	RV_PRICE DECIMAL(3, 1) NOT NULL,	/* 별점(가격) */
	RV_TASTE DECIMAL(3, 1) NOT NULL,	/* 별점(맛) */
	RV_VIBE DECIMAL(3, 1) NOT NULL,		/* 별점(분위기) */
	RV_KIND DECIMAL(3, 1) NOT NULL,		/* 별점(친절도) */
	RV_CONTENT VARCHAR2(200) NOT NULL,
	--	FK 제약조건
	CONSTRAINT FK_REVIEW_RESERVATION
		FOREIGN KEY (R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME)
		REFERENCES RESERVATION_TB (R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME)
		ON DELETE CASCADE,
	-- 별점 범위(0~5) 제한
    CONSTRAINT CHK_PRICE_RANGE CHECK (RV_PRICE BETWEEN 0.0 AND 5.0),
    CONSTRAINT CHK_TASTE_RANGE CHECK (RV_TASTE BETWEEN 0.0 AND 5.0),
    CONSTRAINT CHK_VIBE_RANGE CHECK (RV_VIBE BETWEEN 0.0 AND 5.0),
    CONSTRAINT CHK_KIND_RANGE CHECK (RV_KIND BETWEEN 0.0 AND 5.0)
);


-- RV_NO 시퀀스 생성
CREATE SEQUENCE RV_NO_SEQ
INCREMENT BY 1
START WITH 1
NOCYCLE
NOCACHE;


-- REVIEW 더미 데이터 생성
INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 1,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 1;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 2,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 2;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 3,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 3;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 4,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 4;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 5,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 5;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 6,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 6;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 7,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 7;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 8,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 8;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 9,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 9;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 10,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 10;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 11,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 11;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 12,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 12;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 13,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 13;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 14,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 14;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 15,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 15;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 16,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 16;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 17,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 17;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 18,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 18;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 19,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 19;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 20,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 20;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 21,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 21;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 22,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 22;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 23,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 23;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 24,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 24;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 25,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 25;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 26,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 26;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 27,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 27;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 28,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 28;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 29,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 29;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 30,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 30;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 31,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 31;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 32,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 32;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 33,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 33;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 34,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 34;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 35,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 35;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 36,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 36;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 37,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 37;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 38,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 38;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 39,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 39;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 40,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 40;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 41,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 41;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 42,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 42;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 43,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 43;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 44,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 44;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 45,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 45;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 46,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 46;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 47,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 47;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 48,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 48;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 49,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 49;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 50,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 50;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 51,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 51;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 52,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 52;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 53,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 53;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 54,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 54;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 55,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 55;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 56,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 56;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 57,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 57;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 58,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 58;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 59,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 59;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 60,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 60;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 61,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 61;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 62,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 62;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 63,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 63;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 64,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 64;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 65,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 65;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 66,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 66;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 67,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 67;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 68,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 68;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 69,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 69;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 70,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 70;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 71,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 71;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 72,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 72;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 73,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 73;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 74,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 74;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 75,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 75;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 76,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 76;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 77,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 77;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 78,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 78;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 79,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 79;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 80,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 80;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 81,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 81;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 82,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 82;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 83,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 83;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 84,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 84;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 85,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 85;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 86,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 86;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 87,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 87;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 88,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 88;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 89,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 89;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 90,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 90;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 91,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 91;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 92,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 92;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 93,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 93;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 94,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 94;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 95,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 95;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 96,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 96;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 97,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 97;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 98,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 98;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 99,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 99;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 100,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 100;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 101,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 101;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 102,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 102;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 103,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 103;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 104,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 104;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 105,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 105;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 106,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 106;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 107,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 107;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 108,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 108;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 109,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 109;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 110,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 110;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 111,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 111;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 112,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 112;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 113,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 113;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 114,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 114;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 115,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 115;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 116,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 116;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 117,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 117;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 118,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 118;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 119,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 119;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 120,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 120;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 121,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 121;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 122,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 122;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 123,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 123;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 124,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 124;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 125,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 125;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 126,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 126;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 127,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 127;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 128,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 128;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 129,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 129;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 130,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 130;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 131,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 131;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 132,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 132;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 133,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 133;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 134,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 134;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 135,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 135;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 136,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 136;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 137,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 137;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 138,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 138;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 139,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 139;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 140,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 140;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 141,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 141;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 142,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 142;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 143,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 143;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 144,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 144;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 145,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 145;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 146,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 146;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 147,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 147;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 148,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 148;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 149,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 149;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 150,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 150;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 151,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 151;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 152,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 152;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 153,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 153;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 154,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 154;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 155,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 155;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 156,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 156;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 157,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 157;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 158,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 158;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 159,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 159;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 160,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 160;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 161,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 161;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 162,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 162;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 163,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 163;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 164,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 164;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 165,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 165;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 166,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 166;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 167,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 167;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 168,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 168;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 169,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 169;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 170,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 170;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 171,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 171;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 172,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 172;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 173,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 173;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 174,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 174;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 175,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 175;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 176,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 176;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 177,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 177;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 178,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 178;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 179,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 179;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 180,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 180;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 181,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 181;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 182,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 182;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 183,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 183;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 184,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 184;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 185,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 185;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 186,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 186;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 187,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 187;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 188,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 188;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 189,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 189;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 190,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 190;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 191,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 191;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 192,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 192;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 193,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 193;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 194,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 194;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 195,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 195;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 196,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 196;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 197,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 197;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 198,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 198;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 199,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 199;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 200,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 200;









INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 201,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 201;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 202,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 202;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 203,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 203;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 204,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 204;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 205,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 205;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 206,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 206;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 207,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 207;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 208,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 208;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 209,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 209;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 210,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 210;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 211,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 211;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 212,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 212;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 213,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 213;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 214,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 214;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 215,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 215;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 216,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 216;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 217,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 217;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 218,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 218;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 219,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 219;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 220,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 220;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 221,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 221;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 222,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 222;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 223,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 223;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 224,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 224;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 225,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 225;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 226,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 226;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 227,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 227;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 228,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 228;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 229,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 229;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 230,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 230;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 231,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 231;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 232,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 232;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 233,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 233;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 234,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 234;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 235,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 235;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 236,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 236;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 237,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 237;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 238,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 238;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 239,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 239;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 240,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 240;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 241,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 241;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 242,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 242;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 243,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 243;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 244,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 244;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 245,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 245;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 246,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 246;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 247,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 247;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 248,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 248;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 249,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 249;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 250,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 250;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 251,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 251;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 252,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 252;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 253,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 253;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 254,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 254;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 255,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 255;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 256,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 256;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 257,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 257;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 258,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 258;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 259,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 259;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 260,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 260;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 261,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 261;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 262,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 262;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 263,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 263;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 264,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 264;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 265,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 265;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 266,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 266;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 267,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.5, 3.5, 4.5, 3.0, '쏘쏘'
FROM RESERVATION_TB R WHERE R.R_NO = 267;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 268,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 3.5, 1.0, '가성비'
FROM RESERVATION_TB R WHERE R.R_NO = 268;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 269,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 4.5, 1.5, 1.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 269;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 270,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 4.0, 4.5, 2.5, 5.0, '이븐하게 익은 스테이크'
FROM RESERVATION_TB R WHERE R.R_NO = 270;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 271,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 4.5, 4.0, 5.0, '좋아요오오오오오오오오'
FROM RESERVATION_TB R WHERE R.R_NO = 271;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 272,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 5.0, 5.0, 5.0, 5.0, '구우우우우우우우웃'
FROM RESERVATION_TB R WHERE R.R_NO = 272;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 273,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 1.0, 2.5, 5.0, '친절하기만 함ㅜㅜㅜㅜ'
FROM RESERVATION_TB R WHERE R.R_NO = 273;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 274,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 2.0, 5.0, 3.5, 1.0, '적잖이 맛은 있고요'
FROM RESERVATION_TB R WHERE R.R_NO = 274;

INSERT INTO REVIEW_TB (RV_NO, RV_DATE, R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME, RV_PRICE, RV_TASTE, RV_VIBE, RV_KIND, RV_CONTENT)
SELECT RV_NO_SEQ.NEXTVAL, SYSDATE, 275,
R.R_TIME, R.R_SUBMIT_TIME, R.USER_ID, R.STORE_NAME, 3.0, 4.0, 1.5, 0.0, '이븐하게 익은 스떼이끄와 빈티지 지리는 와인의 조합 대환장'
FROM RESERVATION_TB R WHERE R.R_NO = 275;

-- REVIEW 테스트용 쿼리문
SELECT * FROM REVIEW_TB;					/* 전체 데이터 조회 */

DELETE FROM REVIEW_TB WHERE RV_NO = '5'; 	/* 리뷰번호 단위로 데이터 삭제 */

DROP SEQUENCE RV_NO_SEQ;					/* 리뷰 시퀀스 삭제 */

DROP TABLE REVIEW_TB;						/* 리뷰 테이블 삭제 */

COMMIT;

-- 리뷰 수정 테스트(5번리뷰)
UPDATE REVIEW_TB SET rv_price = 3.0, rv_taste = 4.0, rv_vibe = 1.5, rv_kind = 0 WHERE rv_no = 5;

-- 트리거 생성이 아닌 View 생성 선택 이유: 리뷰 변경 후 즉각 반영됨, 코드 간결
-- View 생성
-- 평점 항목 평균 계산 후 소수점 첫째 자리까지 반올림
-- 각 STORE_NAME 별로 그룹화해서 평균 평점 계산
-- V_STORE_AVG라는 이름으로 View 생성
CREATE OR REPLACE VIEW V_STORE_AVG AS
SELECT 
    STORE_NAME, 
    ROUND(AVG((RV_PRICE + RV_TASTE + RV_VIBE + RV_KIND) / 4), 1) AS average_rating
FROM REVIEW_TB
GROUP BY STORE_NAME;


DROP VIEW V_STORE_AVG;
