-- RESERVATION 테이블 생성
CREATE TABLE RESERVATION_TB (
    R_NO INTEGER NOT NULL PRIMARY KEY,            								/* 예약번호 */
    R_TIME VARCHAR2(20) NOT NULL,                        						/* 예약 시간 (날짜와 시간 포함) */
    R_PERSON_CNT INTEGER NOT NULL,             				   					/* 예약 인원수 */
    R_SUBMIT_TIME DATE DEFAULT SYSDATE,											/* 예약버튼 누른 시간 */
    USER_ID VARCHAR2(20) NOT NULL,                								/* 예약자ID */
    USER_NAME VARCHAR2(20) NOT NULL,             								/* 예약자명 */
	STORE_NO INTEGER NOT NULL, 													/* 매장번호 */
    STORE_NAME VARCHAR2(100) NOT NULL,             								/* 매장명 */
    STORE_PHONE VARCHAR2(15) NOT NULL,         			   						/* 매장 전화번호 */
    BRAND_NAME VARCHAR2(20) NOT NULL,             								/* 브랜드명 */
    -- FK 제약 조건
    CONSTRAINT FK_RESERVATION_USER
        FOREIGN KEY (USER_ID, USER_NAME)
        REFERENCES USER_TB (USER_ID, USER_NAME)
        ON DELETE CASCADE,
    CONSTRAINT FK_RESERVATION_STORE
        FOREIGN KEY (STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
        REFERENCES STORE_TB (STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
        ON DELETE CASCADE,
    -- UNIQUE 제약조건
    CONSTRAINT UNIQUE_RESERVATION1 UNIQUE (R_NO, R_TIME, R_SUBMIT_TIME, USER_ID, STORE_NAME) 	/* REVIEW */
);


-- R_NO 시퀀스 생성
CREATE SEQUENCE R_NO_SEQ
INCREMENT BY 1
START WITH 1
NOCYCLE
NOCACHE;


--RESERVATION 더미 데이터 생성
INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 1, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 1;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 3, SYSDATE, 'testid01',
U.USER_NAME, 2, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 2;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 3, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 3;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 4, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 4;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 5, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 5;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 3, SYSDATE, 'testid01',
U.USER_NAME, 6, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 6;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 7, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 7;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 8, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 8;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 9, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 9;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 10, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 10;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '15', 4, SYSDATE, 'testid01',
U.USER_NAME, 11, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 11;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '15', 3, SYSDATE, 'testid01',
U.USER_NAME, 12, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 12;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '15', 2, SYSDATE, 'testid01',
U.USER_NAME, 13, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 13;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '15', 3, SYSDATE, 'testid01',
U.USER_NAME, 14, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 14;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 15, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 15;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 5, SYSDATE, 'testid01',
U.USER_NAME, 16, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 16;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 17, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 17;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 3, SYSDATE, 'testid01',
U.USER_NAME, 18, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 18;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 3, SYSDATE, 'testid01',
U.USER_NAME, 19, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 19;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 20, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 20;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid01',
U.USER_NAME, 21, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 21;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 5, SYSDATE, 'testid01',
U.USER_NAME, 22, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 22;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid01',
U.USER_NAME, 23, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 23;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 1, SYSDATE, 'testid01',
U.USER_NAME, 24, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 24;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 7, SYSDATE, 'testid01',
U.USER_NAME, 25, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 25;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '15', 4, SYSDATE, 'testid01',
U.USER_NAME, 26, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 26;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 3, SYSDATE, 'testid01',
U.USER_NAME, 27, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 27;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 2, SYSDATE, 'testid01',
U.USER_NAME, 28, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 28;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 29, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 29;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 30, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 30;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 31, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 31;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 32, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 32;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 33, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 33;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 34, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 34;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 35, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 35;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 36, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 36;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 37, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 37;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 38, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 38;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 39, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 39;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 40, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 40;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 41, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 41;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 42, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 42;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 43, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 43;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 44, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 44;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 45, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 45;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 46, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 46;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 47, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 47;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 48, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 48;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 49, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 49;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 50, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 50;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 51, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 51;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 52, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 52;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 53, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 53;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 54, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 54;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 55, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 55;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 56, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 56;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 57, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 57;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 58, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 58;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 59, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 59;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 60, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 60;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 61, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 61;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 62, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 62;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 63, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 63;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 64, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 64;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 65, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 65;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 66, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 66;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 67, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 67;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 68, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 68;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 69, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 69;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 70, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 70;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 71, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 71;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 72, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 72;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 73, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 73;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 74, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 74;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 75, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 75;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 76, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 76;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 77, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 77;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 78, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 78;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 79, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 79;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 80, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 80;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 81, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 81;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 82, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 82;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 83, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 83;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 84, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 84;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 85, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 85;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 86, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 86;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 87, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 87;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 88, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 88;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 89, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 89;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 90, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 90;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 91, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 91;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 92, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 92;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 93, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 93;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 94, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 94;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 95, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 95;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 96, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 96;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '11', 2, SYSDATE, 'testid03',
U.USER_NAME, 97, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 97;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 98, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 98;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 99, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 99;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '09', 2, SYSDATE, 'testid03',
U.USER_NAME, 100, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 100;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 101, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 101;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 3, SYSDATE, 'testid04',
U.USER_NAME, 102, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 102;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 103, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 103;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 104, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 104;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 105, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 105;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 3, SYSDATE, 'testid04',
U.USER_NAME, 106, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 106;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 107, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 107;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 108, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 108;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 109, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 109;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 110, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 110;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 111, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 111;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 3, SYSDATE, 'testid04',
U.USER_NAME, 112, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 112;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 113, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 113;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 114, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 114;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 115, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 115;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 3, SYSDATE, 'testid04',
U.USER_NAME, 116, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 116;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 117, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 117;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 118, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 118;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 119, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 119;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid04',
U.USER_NAME, 120, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 120;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid05',
U.USER_NAME, 121, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 121;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 5, SYSDATE, 'testid05',
U.USER_NAME, 122, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 122;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid05',
U.USER_NAME, 123, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 123;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 1, SYSDATE, 'testid05',
U.USER_NAME, 124, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 124;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 7, SYSDATE, 'testid05',
U.USER_NAME, 125, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 125;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '15', 4, SYSDATE, 'testid05',
U.USER_NAME, 126, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 126;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 3, SYSDATE, 'testid05',
U.USER_NAME, 127, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 127;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 2, SYSDATE, 'testid05',
U.USER_NAME, 128, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 128;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid05',
U.USER_NAME, 129, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 129;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid05',
U.USER_NAME, 130, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 130;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 131, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 131;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 132, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 132;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 133, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 133;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 134, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 134;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 135, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 135;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 136, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 136;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 137, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 137;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 138, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 138;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 139, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 139;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid01',
U.USER_NAME, 140, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 140;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 141, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 141;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 142, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 142;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 143, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 143;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 144, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 144;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 145, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 145;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 146, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 146;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 147, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 147;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 148, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 148;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 149, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 149;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '14', 2, SYSDATE, 'testid02',
U.USER_NAME, 150, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 150;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 151, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 151;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 152, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 152;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 153, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 153;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 154, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 154;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 155, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 155;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 156, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 156;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 157, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 157;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 158, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 158;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 159, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 159;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 160, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 160;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 161, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 161;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 162, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 162;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 163, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 163;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 164, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 164;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 165, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 165;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 166, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 166;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 167, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 167;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 168, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 168;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 169, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 169;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 170, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 170;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 171, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 171;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 172, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 172;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 173, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 173;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 174, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 174;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 175, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 175;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 176, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 176;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 177, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 177;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 178, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 178;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 179, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 179;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 180, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 180;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 181, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 181;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 182, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 182;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 183, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 183;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 184, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 184;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 185, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 185;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 186, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 186;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 187, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 187;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 188, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 188;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 189, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 189;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid06',
U.USER_NAME, 190, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid06' AND S.STORE_NO = 190;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 191, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 191;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 192, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 192;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 193, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 193;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 194, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 194;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 195, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 195;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 196, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 196;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 197, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 197;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 198, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 198;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 199, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 199;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 2, SYSDATE, 'testid07',
U.USER_NAME, 200, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid07' AND S.STORE_NO = 200;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 3, SYSDATE, 'testid08',
U.USER_NAME, 201, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 201;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 3, SYSDATE, 'testid08',
U.USER_NAME, 202, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 202;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 3, SYSDATE, 'testid08',
U.USER_NAME, 203, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 203;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '22', 3, SYSDATE, 'testid08',
U.USER_NAME, 204, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 204;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid08',
U.USER_NAME, 205, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 205;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 3, SYSDATE, 'testid08',
U.USER_NAME, 206, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 206;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid08',
U.USER_NAME, 207, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 207;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid08',
U.USER_NAME, 208, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 208;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid08',
U.USER_NAME, 209, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 209;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid08',
U.USER_NAME, 210, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid08' AND S.STORE_NO = 210;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 211, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 211;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 3, SYSDATE, 'testid09',
U.USER_NAME, 212, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 212;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 213, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 213;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 214, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 214;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 215, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 215;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 3, SYSDATE, 'testid09',
U.USER_NAME, 216, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 216;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 217, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 217;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 218, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 218;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 219, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 219;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '17', 3, SYSDATE, 'testid09',
U.USER_NAME, 220, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid09' AND S.STORE_NO = 220;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 3, SYSDATE, 'testid10',
U.USER_NAME, 221, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 221;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 5, SYSDATE, 'testid10',
U.USER_NAME, 222, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 222;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid10',
U.USER_NAME, 223, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 223;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 1, SYSDATE, 'testid10',
U.USER_NAME, 224, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 224;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 7, SYSDATE, 'testid10',
U.USER_NAME, 225, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 225;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 4, SYSDATE, 'testid10',
U.USER_NAME, 226, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 226;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 3, SYSDATE, 'testid10',
U.USER_NAME, 227, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 227;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid10',
U.USER_NAME, 228, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 228;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid10',
U.USER_NAME, 229, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 229;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid10',
U.USER_NAME, 230, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid10' AND S.STORE_NO = 230;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid01',
U.USER_NAME, 231, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 231;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid01',
U.USER_NAME, 232, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 232;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid01',
U.USER_NAME, 233, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 233;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid01',
U.USER_NAME, 234, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 234;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '12', 2, SYSDATE, 'testid01',
U.USER_NAME, 235, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 235;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid01',
U.USER_NAME, 236, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 236;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid01',
U.USER_NAME, 237, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 237;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid01',
U.USER_NAME, 238, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 238;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid01',
U.USER_NAME, 239, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 239;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid01',
U.USER_NAME, 240, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid01' AND S.STORE_NO = 240;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid02',
U.USER_NAME, 241, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 241;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid02',
U.USER_NAME, 242, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 242;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid02',
U.USER_NAME, 243, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 243;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid02',
U.USER_NAME, 244, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 244;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid02',
U.USER_NAME, 245, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 245;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid02',
U.USER_NAME, 246, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 246;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid02',
U.USER_NAME, 247, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 247;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid02',
U.USER_NAME, 248, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 248;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid02',
U.USER_NAME, 249, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 249;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid02',
U.USER_NAME, 250, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid02' AND S.STORE_NO = 250;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 251, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 251;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 252, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 252;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 253, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 253;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 254, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 254;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 255, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 255;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 256, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 256;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 257, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 257;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 258, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 258;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '13', 2, SYSDATE, 'testid03',
U.USER_NAME, 259, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 259;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '20', 2, SYSDATE, 'testid03',
U.USER_NAME, 260, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid03' AND S.STORE_NO = 260;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 261, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 261;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 262, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 262;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 263, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 263;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 264, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 264;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 265, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 265;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 266, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 266;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 267, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 267;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 268, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 268;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 269, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 269;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '19', 2, SYSDATE, 'testid04',
U.USER_NAME, 270, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid04' AND S.STORE_NO = 270;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 271, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 271;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 272, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 272;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 273, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 273;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 274, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 274;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 275, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 275;

INSERT INTO RESERVATION_TB (R_NO, R_TIME, R_PERSON_CNT, R_SUBMIT_TIME, USER_ID, USER_NAME, STORE_NO, STORE_NAME, STORE_PHONE, BRAND_NAME)
SELECT R_NO_SEQ.NEXTVAL, '18', 2, SYSDATE, 'testid05',
U.USER_NAME, 276, S.STORE_NAME, S.STORE_PHONE, S.BRAND_NAME FROM USER_TB U, STORE_TB S WHERE U.USER_ID = 'testid05' AND S.STORE_NO = 276;


-- RESERVATION 테스트용 쿼리문
SELECT * FROM RESERVATION_TB;	/* 전체 데이터 조회 */

DELETE FROM RESERVATION_TB WHERE STORE_NO = '6'; /* 매장명 단위로 데이터 삭제 */

DROP SEQUENCE R_NO_SEQ;			/* R_NO 시퀀스 삭제 */

DROP TABLE RESERVATION_TB;		/* RESERVATION 테이블 삭제 */

COMMIT;
